### ISSUE TITLE
Create UI vision

### ISSUE THREAD

**Issue by marwasha** [marwasha/LeChef3000#2]
Use whiteboard/jamboard to draw up what we expect the UI to look like

**Comment by okyang** [comment]
# 📔 Summary

We will have two UI states:
1. Live temperature reading (when the grill is on)
2. Update grill parameters (when the grill is not on)

To interact with the UI we will use the [WIO terminal 5-way](https://wiki.seeedstudio.com/Wio-Terminal-Switch/) switch to update those parameters. 

## 🔥 Grilling Status UI 

Features:
- Internal temperature Indicator
- E-stop

## 💻 Update Parameters UI

The UI will be its own class that will be passed references to the grill parameters. The reference parameters will also be updated by the UI class. 

Features:
- Send parameters to update
